// Code generated by protoc-gen-go. DO NOT EDIT.
// source: registry.proto

package nproto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type File struct {
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{0}
}

func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (m *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(m, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *File) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type SaveFilesRequest struct {
	ClusterID            string   `protobuf:"bytes,1,opt,name=clusterID,proto3" json:"clusterID,omitempty"`
	Channel              string   `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	Files                []*File  `protobuf:"bytes,3,rep,name=files,proto3" json:"files,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveFilesRequest) Reset()         { *m = SaveFilesRequest{} }
func (m *SaveFilesRequest) String() string { return proto.CompactTextString(m) }
func (*SaveFilesRequest) ProtoMessage()    {}
func (*SaveFilesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{1}
}

func (m *SaveFilesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveFilesRequest.Unmarshal(m, b)
}
func (m *SaveFilesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveFilesRequest.Marshal(b, m, deterministic)
}
func (m *SaveFilesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveFilesRequest.Merge(m, src)
}
func (m *SaveFilesRequest) XXX_Size() int {
	return xxx_messageInfo_SaveFilesRequest.Size(m)
}
func (m *SaveFilesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveFilesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SaveFilesRequest proto.InternalMessageInfo

func (m *SaveFilesRequest) GetClusterID() string {
	if m != nil {
		return m.ClusterID
	}
	return ""
}

func (m *SaveFilesRequest) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *SaveFilesRequest) GetFiles() []*File {
	if m != nil {
		return m.Files
	}
	return nil
}

type SaveFilesReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveFilesReply) Reset()         { *m = SaveFilesReply{} }
func (m *SaveFilesReply) String() string { return proto.CompactTextString(m) }
func (*SaveFilesReply) ProtoMessage()    {}
func (*SaveFilesReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{2}
}

func (m *SaveFilesReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveFilesReply.Unmarshal(m, b)
}
func (m *SaveFilesReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveFilesReply.Marshal(b, m, deterministic)
}
func (m *SaveFilesReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveFilesReply.Merge(m, src)
}
func (m *SaveFilesReply) XXX_Size() int {
	return xxx_messageInfo_SaveFilesReply.Size(m)
}
func (m *SaveFilesReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveFilesReply.DiscardUnknown(m)
}

var xxx_messageInfo_SaveFilesReply proto.InternalMessageInfo

type GetFilesRequest struct {
	ClusterID            string   `protobuf:"bytes,1,opt,name=clusterID,proto3" json:"clusterID,omitempty"`
	Channel              string   `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFilesRequest) Reset()         { *m = GetFilesRequest{} }
func (m *GetFilesRequest) String() string { return proto.CompactTextString(m) }
func (*GetFilesRequest) ProtoMessage()    {}
func (*GetFilesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{3}
}

func (m *GetFilesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFilesRequest.Unmarshal(m, b)
}
func (m *GetFilesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFilesRequest.Marshal(b, m, deterministic)
}
func (m *GetFilesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFilesRequest.Merge(m, src)
}
func (m *GetFilesRequest) XXX_Size() int {
	return xxx_messageInfo_GetFilesRequest.Size(m)
}
func (m *GetFilesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFilesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFilesRequest proto.InternalMessageInfo

func (m *GetFilesRequest) GetClusterID() string {
	if m != nil {
		return m.ClusterID
	}
	return ""
}

func (m *GetFilesRequest) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

type GetFilesReply struct {
	Files                []*File  `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFilesReply) Reset()         { *m = GetFilesReply{} }
func (m *GetFilesReply) String() string { return proto.CompactTextString(m) }
func (*GetFilesReply) ProtoMessage()    {}
func (*GetFilesReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{4}
}

func (m *GetFilesReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFilesReply.Unmarshal(m, b)
}
func (m *GetFilesReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFilesReply.Marshal(b, m, deterministic)
}
func (m *GetFilesReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFilesReply.Merge(m, src)
}
func (m *GetFilesReply) XXX_Size() int {
	return xxx_messageInfo_GetFilesReply.Size(m)
}
func (m *GetFilesReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFilesReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetFilesReply proto.InternalMessageInfo

func (m *GetFilesReply) GetFiles() []*File {
	if m != nil {
		return m.Files
	}
	return nil
}

type SetMessageRequest struct {
	ClusterID            string   `protobuf:"bytes,1,opt,name=clusterID,proto3" json:"clusterID,omitempty"`
	Channel              string   `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetMessageRequest) Reset()         { *m = SetMessageRequest{} }
func (m *SetMessageRequest) String() string { return proto.CompactTextString(m) }
func (*SetMessageRequest) ProtoMessage()    {}
func (*SetMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{5}
}

func (m *SetMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetMessageRequest.Unmarshal(m, b)
}
func (m *SetMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetMessageRequest.Marshal(b, m, deterministic)
}
func (m *SetMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetMessageRequest.Merge(m, src)
}
func (m *SetMessageRequest) XXX_Size() int {
	return xxx_messageInfo_SetMessageRequest.Size(m)
}
func (m *SetMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetMessageRequest proto.InternalMessageInfo

func (m *SetMessageRequest) GetClusterID() string {
	if m != nil {
		return m.ClusterID
	}
	return ""
}

func (m *SetMessageRequest) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *SetMessageRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type SetMessageReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetMessageReply) Reset()         { *m = SetMessageReply{} }
func (m *SetMessageReply) String() string { return proto.CompactTextString(m) }
func (*SetMessageReply) ProtoMessage()    {}
func (*SetMessageReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{6}
}

func (m *SetMessageReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetMessageReply.Unmarshal(m, b)
}
func (m *SetMessageReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetMessageReply.Marshal(b, m, deterministic)
}
func (m *SetMessageReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetMessageReply.Merge(m, src)
}
func (m *SetMessageReply) XXX_Size() int {
	return xxx_messageInfo_SetMessageReply.Size(m)
}
func (m *SetMessageReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SetMessageReply.DiscardUnknown(m)
}

var xxx_messageInfo_SetMessageReply proto.InternalMessageInfo

type GetMessageRequest struct {
	ClusterID            string   `protobuf:"bytes,1,opt,name=clusterID,proto3" json:"clusterID,omitempty"`
	Channel              string   `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMessageRequest) Reset()         { *m = GetMessageRequest{} }
func (m *GetMessageRequest) String() string { return proto.CompactTextString(m) }
func (*GetMessageRequest) ProtoMessage()    {}
func (*GetMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{7}
}

func (m *GetMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMessageRequest.Unmarshal(m, b)
}
func (m *GetMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMessageRequest.Marshal(b, m, deterministic)
}
func (m *GetMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMessageRequest.Merge(m, src)
}
func (m *GetMessageRequest) XXX_Size() int {
	return xxx_messageInfo_GetMessageRequest.Size(m)
}
func (m *GetMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMessageRequest proto.InternalMessageInfo

func (m *GetMessageRequest) GetClusterID() string {
	if m != nil {
		return m.ClusterID
	}
	return ""
}

func (m *GetMessageRequest) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

type GetMessageReply struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMessageReply) Reset()         { *m = GetMessageReply{} }
func (m *GetMessageReply) String() string { return proto.CompactTextString(m) }
func (*GetMessageReply) ProtoMessage()    {}
func (*GetMessageReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{8}
}

func (m *GetMessageReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMessageReply.Unmarshal(m, b)
}
func (m *GetMessageReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMessageReply.Marshal(b, m, deterministic)
}
func (m *GetMessageReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMessageReply.Merge(m, src)
}
func (m *GetMessageReply) XXX_Size() int {
	return xxx_messageInfo_GetMessageReply.Size(m)
}
func (m *GetMessageReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMessageReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetMessageReply proto.InternalMessageInfo

func (m *GetMessageReply) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetChannelDataRequest struct {
	ClusterID            string   `protobuf:"bytes,1,opt,name=clusterID,proto3" json:"clusterID,omitempty"`
	Channel              string   `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetChannelDataRequest) Reset()         { *m = GetChannelDataRequest{} }
func (m *GetChannelDataRequest) String() string { return proto.CompactTextString(m) }
func (*GetChannelDataRequest) ProtoMessage()    {}
func (*GetChannelDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{9}
}

func (m *GetChannelDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetChannelDataRequest.Unmarshal(m, b)
}
func (m *GetChannelDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetChannelDataRequest.Marshal(b, m, deterministic)
}
func (m *GetChannelDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetChannelDataRequest.Merge(m, src)
}
func (m *GetChannelDataRequest) XXX_Size() int {
	return xxx_messageInfo_GetChannelDataRequest.Size(m)
}
func (m *GetChannelDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetChannelDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetChannelDataRequest proto.InternalMessageInfo

func (m *GetChannelDataRequest) GetClusterID() string {
	if m != nil {
		return m.ClusterID
	}
	return ""
}

func (m *GetChannelDataRequest) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

type GetChannelDataReply struct {
	ClusterID            string   `protobuf:"bytes,1,opt,name=clusterID,proto3" json:"clusterID,omitempty"`
	Channel              string   `protobuf:"bytes,3,opt,name=channel,proto3" json:"channel,omitempty"`
	Message              string   `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Files                []*File  `protobuf:"bytes,5,rep,name=files,proto3" json:"files,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetChannelDataReply) Reset()         { *m = GetChannelDataReply{} }
func (m *GetChannelDataReply) String() string { return proto.CompactTextString(m) }
func (*GetChannelDataReply) ProtoMessage()    {}
func (*GetChannelDataReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{10}
}

func (m *GetChannelDataReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetChannelDataReply.Unmarshal(m, b)
}
func (m *GetChannelDataReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetChannelDataReply.Marshal(b, m, deterministic)
}
func (m *GetChannelDataReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetChannelDataReply.Merge(m, src)
}
func (m *GetChannelDataReply) XXX_Size() int {
	return xxx_messageInfo_GetChannelDataReply.Size(m)
}
func (m *GetChannelDataReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetChannelDataReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetChannelDataReply proto.InternalMessageInfo

func (m *GetChannelDataReply) GetClusterID() string {
	if m != nil {
		return m.ClusterID
	}
	return ""
}

func (m *GetChannelDataReply) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *GetChannelDataReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetChannelDataReply) GetFiles() []*File {
	if m != nil {
		return m.Files
	}
	return nil
}

type SetChannelDataRequest struct {
	ClusterID            string   `protobuf:"bytes,1,opt,name=clusterID,proto3" json:"clusterID,omitempty"`
	Channel              string   `protobuf:"bytes,3,opt,name=channel,proto3" json:"channel,omitempty"`
	Message              string   `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Files                []*File  `protobuf:"bytes,5,rep,name=files,proto3" json:"files,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetChannelDataRequest) Reset()         { *m = SetChannelDataRequest{} }
func (m *SetChannelDataRequest) String() string { return proto.CompactTextString(m) }
func (*SetChannelDataRequest) ProtoMessage()    {}
func (*SetChannelDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{11}
}

func (m *SetChannelDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetChannelDataRequest.Unmarshal(m, b)
}
func (m *SetChannelDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetChannelDataRequest.Marshal(b, m, deterministic)
}
func (m *SetChannelDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetChannelDataRequest.Merge(m, src)
}
func (m *SetChannelDataRequest) XXX_Size() int {
	return xxx_messageInfo_SetChannelDataRequest.Size(m)
}
func (m *SetChannelDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetChannelDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetChannelDataRequest proto.InternalMessageInfo

func (m *SetChannelDataRequest) GetClusterID() string {
	if m != nil {
		return m.ClusterID
	}
	return ""
}

func (m *SetChannelDataRequest) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *SetChannelDataRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *SetChannelDataRequest) GetFiles() []*File {
	if m != nil {
		return m.Files
	}
	return nil
}

type SetChannelDataReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetChannelDataReply) Reset()         { *m = SetChannelDataReply{} }
func (m *SetChannelDataReply) String() string { return proto.CompactTextString(m) }
func (*SetChannelDataReply) ProtoMessage()    {}
func (*SetChannelDataReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{12}
}

func (m *SetChannelDataReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetChannelDataReply.Unmarshal(m, b)
}
func (m *SetChannelDataReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetChannelDataReply.Marshal(b, m, deterministic)
}
func (m *SetChannelDataReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetChannelDataReply.Merge(m, src)
}
func (m *SetChannelDataReply) XXX_Size() int {
	return xxx_messageInfo_SetChannelDataReply.Size(m)
}
func (m *SetChannelDataReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SetChannelDataReply.DiscardUnknown(m)
}

var xxx_messageInfo_SetChannelDataReply proto.InternalMessageInfo

type GetChannelsRequest struct {
	ClusterID            string   `protobuf:"bytes,1,opt,name=clusterID,proto3" json:"clusterID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetChannelsRequest) Reset()         { *m = GetChannelsRequest{} }
func (m *GetChannelsRequest) String() string { return proto.CompactTextString(m) }
func (*GetChannelsRequest) ProtoMessage()    {}
func (*GetChannelsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{13}
}

func (m *GetChannelsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetChannelsRequest.Unmarshal(m, b)
}
func (m *GetChannelsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetChannelsRequest.Marshal(b, m, deterministic)
}
func (m *GetChannelsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetChannelsRequest.Merge(m, src)
}
func (m *GetChannelsRequest) XXX_Size() int {
	return xxx_messageInfo_GetChannelsRequest.Size(m)
}
func (m *GetChannelsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetChannelsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetChannelsRequest proto.InternalMessageInfo

func (m *GetChannelsRequest) GetClusterID() string {
	if m != nil {
		return m.ClusterID
	}
	return ""
}

type GetChannelsReply struct {
	Channels             []string `protobuf:"bytes,1,rep,name=Channels,proto3" json:"Channels,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetChannelsReply) Reset()         { *m = GetChannelsReply{} }
func (m *GetChannelsReply) String() string { return proto.CompactTextString(m) }
func (*GetChannelsReply) ProtoMessage()    {}
func (*GetChannelsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{14}
}

func (m *GetChannelsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetChannelsReply.Unmarshal(m, b)
}
func (m *GetChannelsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetChannelsReply.Marshal(b, m, deterministic)
}
func (m *GetChannelsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetChannelsReply.Merge(m, src)
}
func (m *GetChannelsReply) XXX_Size() int {
	return xxx_messageInfo_GetChannelsReply.Size(m)
}
func (m *GetChannelsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetChannelsReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetChannelsReply proto.InternalMessageInfo

func (m *GetChannelsReply) GetChannels() []string {
	if m != nil {
		return m.Channels
	}
	return nil
}

type Cluster struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Servers              []string `protobuf:"bytes,4,rep,name=servers,proto3" json:"servers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Cluster) Reset()         { *m = Cluster{} }
func (m *Cluster) String() string { return proto.CompactTextString(m) }
func (*Cluster) ProtoMessage()    {}
func (*Cluster) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{15}
}

func (m *Cluster) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cluster.Unmarshal(m, b)
}
func (m *Cluster) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cluster.Marshal(b, m, deterministic)
}
func (m *Cluster) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cluster.Merge(m, src)
}
func (m *Cluster) XXX_Size() int {
	return xxx_messageInfo_Cluster.Size(m)
}
func (m *Cluster) XXX_DiscardUnknown() {
	xxx_messageInfo_Cluster.DiscardUnknown(m)
}

var xxx_messageInfo_Cluster proto.InternalMessageInfo

func (m *Cluster) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Cluster) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Cluster) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Cluster) GetServers() []string {
	if m != nil {
		return m.Servers
	}
	return nil
}

type SaveClusterRequest struct {
	Cluster              *Cluster `protobuf:"bytes,2,opt,name=cluster,proto3" json:"cluster,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveClusterRequest) Reset()         { *m = SaveClusterRequest{} }
func (m *SaveClusterRequest) String() string { return proto.CompactTextString(m) }
func (*SaveClusterRequest) ProtoMessage()    {}
func (*SaveClusterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{16}
}

func (m *SaveClusterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveClusterRequest.Unmarshal(m, b)
}
func (m *SaveClusterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveClusterRequest.Marshal(b, m, deterministic)
}
func (m *SaveClusterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveClusterRequest.Merge(m, src)
}
func (m *SaveClusterRequest) XXX_Size() int {
	return xxx_messageInfo_SaveClusterRequest.Size(m)
}
func (m *SaveClusterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveClusterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SaveClusterRequest proto.InternalMessageInfo

func (m *SaveClusterRequest) GetCluster() *Cluster {
	if m != nil {
		return m.Cluster
	}
	return nil
}

type SaveClusterReply struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveClusterReply) Reset()         { *m = SaveClusterReply{} }
func (m *SaveClusterReply) String() string { return proto.CompactTextString(m) }
func (*SaveClusterReply) ProtoMessage()    {}
func (*SaveClusterReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{17}
}

func (m *SaveClusterReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveClusterReply.Unmarshal(m, b)
}
func (m *SaveClusterReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveClusterReply.Marshal(b, m, deterministic)
}
func (m *SaveClusterReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveClusterReply.Merge(m, src)
}
func (m *SaveClusterReply) XXX_Size() int {
	return xxx_messageInfo_SaveClusterReply.Size(m)
}
func (m *SaveClusterReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveClusterReply.DiscardUnknown(m)
}

var xxx_messageInfo_SaveClusterReply proto.InternalMessageInfo

func (m *SaveClusterReply) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetClusterRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetClusterRequest) Reset()         { *m = GetClusterRequest{} }
func (m *GetClusterRequest) String() string { return proto.CompactTextString(m) }
func (*GetClusterRequest) ProtoMessage()    {}
func (*GetClusterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{18}
}

func (m *GetClusterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetClusterRequest.Unmarshal(m, b)
}
func (m *GetClusterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetClusterRequest.Marshal(b, m, deterministic)
}
func (m *GetClusterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetClusterRequest.Merge(m, src)
}
func (m *GetClusterRequest) XXX_Size() int {
	return xxx_messageInfo_GetClusterRequest.Size(m)
}
func (m *GetClusterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetClusterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetClusterRequest proto.InternalMessageInfo

func (m *GetClusterRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetClusterReply struct {
	Cluster              *Cluster `protobuf:"bytes,1,opt,name=cluster,proto3" json:"cluster,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetClusterReply) Reset()         { *m = GetClusterReply{} }
func (m *GetClusterReply) String() string { return proto.CompactTextString(m) }
func (*GetClusterReply) ProtoMessage()    {}
func (*GetClusterReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{19}
}

func (m *GetClusterReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetClusterReply.Unmarshal(m, b)
}
func (m *GetClusterReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetClusterReply.Marshal(b, m, deterministic)
}
func (m *GetClusterReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetClusterReply.Merge(m, src)
}
func (m *GetClusterReply) XXX_Size() int {
	return xxx_messageInfo_GetClusterReply.Size(m)
}
func (m *GetClusterReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetClusterReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetClusterReply proto.InternalMessageInfo

func (m *GetClusterReply) GetCluster() *Cluster {
	if m != nil {
		return m.Cluster
	}
	return nil
}

type GetClustersRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetClustersRequest) Reset()         { *m = GetClustersRequest{} }
func (m *GetClustersRequest) String() string { return proto.CompactTextString(m) }
func (*GetClustersRequest) ProtoMessage()    {}
func (*GetClustersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{20}
}

func (m *GetClustersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetClustersRequest.Unmarshal(m, b)
}
func (m *GetClustersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetClustersRequest.Marshal(b, m, deterministic)
}
func (m *GetClustersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetClustersRequest.Merge(m, src)
}
func (m *GetClustersRequest) XXX_Size() int {
	return xxx_messageInfo_GetClustersRequest.Size(m)
}
func (m *GetClustersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetClustersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetClustersRequest proto.InternalMessageInfo

type GetClustersReply struct {
	Clusters             []*Cluster `protobuf:"bytes,1,rep,name=clusters,proto3" json:"clusters,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetClustersReply) Reset()         { *m = GetClustersReply{} }
func (m *GetClustersReply) String() string { return proto.CompactTextString(m) }
func (*GetClustersReply) ProtoMessage()    {}
func (*GetClustersReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{21}
}

func (m *GetClustersReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetClustersReply.Unmarshal(m, b)
}
func (m *GetClustersReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetClustersReply.Marshal(b, m, deterministic)
}
func (m *GetClustersReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetClustersReply.Merge(m, src)
}
func (m *GetClustersReply) XXX_Size() int {
	return xxx_messageInfo_GetClustersReply.Size(m)
}
func (m *GetClustersReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetClustersReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetClustersReply proto.InternalMessageInfo

func (m *GetClustersReply) GetClusters() []*Cluster {
	if m != nil {
		return m.Clusters
	}
	return nil
}

func init() {
	proto.RegisterType((*File)(nil), "noptics.File")
	proto.RegisterType((*SaveFilesRequest)(nil), "noptics.SaveFilesRequest")
	proto.RegisterType((*SaveFilesReply)(nil), "noptics.SaveFilesReply")
	proto.RegisterType((*GetFilesRequest)(nil), "noptics.GetFilesRequest")
	proto.RegisterType((*GetFilesReply)(nil), "noptics.GetFilesReply")
	proto.RegisterType((*SetMessageRequest)(nil), "noptics.SetMessageRequest")
	proto.RegisterType((*SetMessageReply)(nil), "noptics.SetMessageReply")
	proto.RegisterType((*GetMessageRequest)(nil), "noptics.GetMessageRequest")
	proto.RegisterType((*GetMessageReply)(nil), "noptics.GetMessageReply")
	proto.RegisterType((*GetChannelDataRequest)(nil), "noptics.GetChannelDataRequest")
	proto.RegisterType((*GetChannelDataReply)(nil), "noptics.GetChannelDataReply")
	proto.RegisterType((*SetChannelDataRequest)(nil), "noptics.SetChannelDataRequest")
	proto.RegisterType((*SetChannelDataReply)(nil), "noptics.SetChannelDataReply")
	proto.RegisterType((*GetChannelsRequest)(nil), "noptics.GetChannelsRequest")
	proto.RegisterType((*GetChannelsReply)(nil), "noptics.GetChannelsReply")
	proto.RegisterType((*Cluster)(nil), "noptics.Cluster")
	proto.RegisterType((*SaveClusterRequest)(nil), "noptics.SaveClusterRequest")
	proto.RegisterType((*SaveClusterReply)(nil), "noptics.SaveClusterReply")
	proto.RegisterType((*GetClusterRequest)(nil), "noptics.GetClusterRequest")
	proto.RegisterType((*GetClusterReply)(nil), "noptics.GetClusterReply")
	proto.RegisterType((*GetClustersRequest)(nil), "noptics.GetClustersRequest")
	proto.RegisterType((*GetClustersReply)(nil), "noptics.GetClustersReply")
}

func init() { proto.RegisterFile("registry.proto", fileDescriptor_41af05d40a615591) }

var fileDescriptor_41af05d40a615591 = []byte{
	// 621 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x96, 0xdf, 0x6f, 0xd3, 0x30,
	0x10, 0xc7, 0x97, 0xfe, 0x58, 0xdb, 0x2b, 0xed, 0x5a, 0x8f, 0x82, 0x1b, 0x26, 0x54, 0x79, 0x42,
	0xaa, 0x10, 0xea, 0x43, 0xe1, 0x15, 0x34, 0x58, 0x45, 0x34, 0x21, 0xc4, 0x94, 0xbc, 0xf1, 0x82,
	0x42, 0x6b, 0x46, 0xa4, 0x2e, 0x2d, 0x89, 0x37, 0xa9, 0xff, 0x03, 0xe2, 0x9f, 0xe4, 0x1f, 0x99,
	0xec, 0xc4, 0x8e, 0x93, 0x78, 0xdd, 0xa4, 0xf6, 0xa9, 0xb1, 0xcf, 0xf7, 0xb9, 0xbb, 0xaf, 0x7d,
	0xa7, 0x42, 0x37, 0xa2, 0x57, 0x41, 0xcc, 0xa2, 0xcd, 0x64, 0x1d, 0xad, 0xd8, 0x0a, 0x35, 0xc2,
	0xd5, 0x9a, 0x05, 0xf3, 0x98, 0x4c, 0xa0, 0xf6, 0x39, 0x58, 0x52, 0x84, 0xa0, 0x16, 0xfa, 0xd7,
	0x14, 0x57, 0x46, 0xd6, 0xb8, 0xe5, 0x8a, 0x6f, 0xbe, 0xb7, 0xf0, 0x99, 0x8f, 0xab, 0x23, 0x6b,
	0xfc, 0xc4, 0x15, 0xdf, 0x64, 0x05, 0x3d, 0xcf, 0xbf, 0xa5, 0xdc, 0x27, 0x76, 0xe9, 0x9f, 0x1b,
	0x1a, 0x33, 0x74, 0x02, 0xad, 0xf9, 0xf2, 0x26, 0x66, 0x34, 0xba, 0x98, 0x61, 0x4b, 0x00, 0xb2,
	0x0d, 0x84, 0xa1, 0x31, 0xff, 0xed, 0x87, 0x21, 0x5d, 0xa6, 0x70, 0xb9, 0x44, 0xa7, 0x50, 0xff,
	0xc5, 0x39, 0xb8, 0x3a, 0xaa, 0x8e, 0xdb, 0xd3, 0xce, 0x24, 0x4d, 0x6a, 0xc2, 0xe9, 0x6e, 0x62,
	0x23, 0x3d, 0xe8, 0x6a, 0x01, 0xd7, 0xcb, 0x0d, 0xb9, 0x80, 0x23, 0x87, 0xb2, 0x7d, 0x64, 0x40,
	0xde, 0x41, 0x27, 0x43, 0xad, 0x97, 0x9b, 0x2c, 0x25, 0x6b, 0x4b, 0x4a, 0x3f, 0xa0, 0xef, 0x51,
	0xf6, 0x95, 0xc6, 0xb1, 0x7f, 0x45, 0x77, 0x15, 0x41, 0x0a, 0x5f, 0xcd, 0x84, 0x27, 0x7d, 0x38,
	0xd2, 0x03, 0xf0, 0xa2, 0xbf, 0x40, 0xdf, 0xd9, 0x57, 0x4c, 0xf2, 0x4a, 0x28, 0xa8, 0xf3, 0x55,
	0x1a, 0x96, 0x96, 0xc6, 0x37, 0x18, 0x38, 0x94, 0x9d, 0x27, 0x4e, 0x33, 0x9f, 0xf9, 0xbb, 0xc6,
	0xfd, 0x6b, 0xc1, 0x71, 0x91, 0xc8, 0x83, 0x3f, 0x9a, 0x57, 0xcd, 0x6b, 0x87, 0xa1, 0x71, 0x9d,
	0x14, 0x81, 0x6b, 0x89, 0x25, 0x5d, 0x66, 0xf7, 0x58, 0xdf, 0x72, 0x8f, 0xff, 0x2c, 0x18, 0x78,
	0xbb, 0x15, 0xb8, 0xdf, 0x84, 0x06, 0x70, 0xec, 0x95, 0xe5, 0x21, 0x53, 0x40, 0x99, 0x6a, 0x8f,
	0x7b, 0xf3, 0x64, 0x02, 0xbd, 0x9c, 0x0f, 0x97, 0xd9, 0x86, 0xa6, 0xdc, 0x10, 0xef, 0xbb, 0xe5,
	0xaa, 0x35, 0x09, 0xa0, 0x71, 0x9e, 0x38, 0xa3, 0x2e, 0x54, 0x82, 0x45, 0x4a, 0xac, 0x04, 0x0b,
	0xe3, 0x68, 0x18, 0x41, 0x7b, 0x41, 0xe3, 0x79, 0x14, 0xac, 0x59, 0xb0, 0x0a, 0x53, 0x19, 0xf4,
	0x2d, 0x2e, 0x45, 0x4c, 0xa3, 0x5b, 0x1a, 0xc5, 0xb8, 0x26, 0x62, 0xc9, 0x25, 0x39, 0x03, 0xc4,
	0x3b, 0x3a, 0x0d, 0x27, 0xcb, 0x79, 0x0d, 0x8d, 0x34, 0x7b, 0x11, 0xa8, 0x3d, 0xed, 0x29, 0x89,
	0xe4, 0x49, 0x79, 0x80, 0x90, 0x64, 0x08, 0x29, 0x02, 0x2f, 0xae, 0x90, 0x35, 0x39, 0x15, 0x0d,
	0x53, 0x08, 0x52, 0x3c, 0xf4, 0x5e, 0x34, 0x42, 0x8e, 0xa3, 0xe5, 0x61, 0x3d, 0x94, 0xc7, 0xd3,
	0xe4, 0x62, 0x92, 0x95, 0xbc, 0x18, 0x72, 0x96, 0x48, 0xaf, 0x76, 0x39, 0xf5, 0x0d, 0x34, 0x53,
	0x27, 0x39, 0x5a, 0xca, 0x58, 0x75, 0x62, 0xfa, 0xbf, 0x0e, 0x9d, 0x4b, 0x3e, 0xa7, 0xdd, 0x74,
	0x6a, 0xa3, 0x8f, 0xd0, 0x52, 0x53, 0x10, 0x0d, 0x95, 0x6b, 0x71, 0x14, 0xdb, 0xcf, 0x4d, 0x26,
	0xfe, 0x86, 0x0e, 0xd0, 0x07, 0x68, 0xca, 0x59, 0x87, 0xb0, 0x3a, 0x56, 0x98, 0xa4, 0xf6, 0x33,
	0x83, 0x25, 0xf1, 0x9f, 0x01, 0x64, 0x43, 0x09, 0xd9, 0x59, 0xa0, 0xe2, 0x58, 0xb2, 0xb1, 0xd1,
	0xa6, 0x28, 0x8e, 0x89, 0xe2, 0x6c, 0xa1, 0x38, 0x25, 0xca, 0x25, 0x74, 0xf3, 0x73, 0x04, 0xbd,
	0xd4, 0x4f, 0x97, 0x3b, 0xda, 0x3e, 0xb9, 0xd7, 0xae, 0x88, 0xde, 0x7d, 0x44, 0xef, 0x01, 0xa2,
	0x67, 0x24, 0x3a, 0xd0, 0xd6, 0x3a, 0x10, 0xbd, 0x30, 0x24, 0xa0, 0x54, 0x1f, 0x9a, 0x8d, 0x0a,
	0xa4, 0xbd, 0x76, 0x0d, 0x54, 0xee, 0x22, 0x7b, 0x68, 0x36, 0xea, 0xda, 0x4b, 0x4e, 0x4e, 0xfb,
	0x02, 0x06, 0x1b, 0x6d, 0xb9, 0xba, 0xd2, 0xb7, 0x5a, 0xa8, 0x2b, 0xdf, 0x0a, 0x85, 0xba, 0xf4,
	0x8e, 0x20, 0x07, 0x9f, 0x9a, 0xdf, 0x0f, 0x43, 0xf1, 0x6f, 0xe4, 0xe7, 0xa1, 0xf8, 0x79, 0x7b,
	0x17, 0x00, 0x00, 0xff, 0xff, 0x49, 0x95, 0xbe, 0xda, 0xa6, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProtoRegistryClient is the client API for ProtoRegistry service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProtoRegistryClient interface {
	SaveFiles(ctx context.Context, in *SaveFilesRequest, opts ...grpc.CallOption) (*SaveFilesReply, error)
	GetFiles(ctx context.Context, in *GetFilesRequest, opts ...grpc.CallOption) (*GetFilesReply, error)
	SetMessage(ctx context.Context, in *SetMessageRequest, opts ...grpc.CallOption) (*SetMessageReply, error)
	GetMessage(ctx context.Context, in *GetMessageRequest, opts ...grpc.CallOption) (*GetMessageReply, error)
	GetChannelData(ctx context.Context, in *GetChannelDataRequest, opts ...grpc.CallOption) (*GetChannelDataReply, error)
	SetChannelData(ctx context.Context, in *SetChannelDataRequest, opts ...grpc.CallOption) (*SetChannelDataReply, error)
	GetChannels(ctx context.Context, in *GetChannelsRequest, opts ...grpc.CallOption) (*GetChannelsReply, error)
	SaveCluster(ctx context.Context, in *SaveClusterRequest, opts ...grpc.CallOption) (*SaveClusterReply, error)
	GetCluster(ctx context.Context, in *GetClusterRequest, opts ...grpc.CallOption) (*GetClusterReply, error)
	GetClusters(ctx context.Context, in *GetClustersRequest, opts ...grpc.CallOption) (*GetClustersReply, error)
}

type protoRegistryClient struct {
	cc *grpc.ClientConn
}

func NewProtoRegistryClient(cc *grpc.ClientConn) ProtoRegistryClient {
	return &protoRegistryClient{cc}
}

func (c *protoRegistryClient) SaveFiles(ctx context.Context, in *SaveFilesRequest, opts ...grpc.CallOption) (*SaveFilesReply, error) {
	out := new(SaveFilesReply)
	err := c.cc.Invoke(ctx, "/noptics.ProtoRegistry/SaveFiles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *protoRegistryClient) GetFiles(ctx context.Context, in *GetFilesRequest, opts ...grpc.CallOption) (*GetFilesReply, error) {
	out := new(GetFilesReply)
	err := c.cc.Invoke(ctx, "/noptics.ProtoRegistry/GetFiles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *protoRegistryClient) SetMessage(ctx context.Context, in *SetMessageRequest, opts ...grpc.CallOption) (*SetMessageReply, error) {
	out := new(SetMessageReply)
	err := c.cc.Invoke(ctx, "/noptics.ProtoRegistry/SetMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *protoRegistryClient) GetMessage(ctx context.Context, in *GetMessageRequest, opts ...grpc.CallOption) (*GetMessageReply, error) {
	out := new(GetMessageReply)
	err := c.cc.Invoke(ctx, "/noptics.ProtoRegistry/GetMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *protoRegistryClient) GetChannelData(ctx context.Context, in *GetChannelDataRequest, opts ...grpc.CallOption) (*GetChannelDataReply, error) {
	out := new(GetChannelDataReply)
	err := c.cc.Invoke(ctx, "/noptics.ProtoRegistry/GetChannelData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *protoRegistryClient) SetChannelData(ctx context.Context, in *SetChannelDataRequest, opts ...grpc.CallOption) (*SetChannelDataReply, error) {
	out := new(SetChannelDataReply)
	err := c.cc.Invoke(ctx, "/noptics.ProtoRegistry/SetChannelData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *protoRegistryClient) GetChannels(ctx context.Context, in *GetChannelsRequest, opts ...grpc.CallOption) (*GetChannelsReply, error) {
	out := new(GetChannelsReply)
	err := c.cc.Invoke(ctx, "/noptics.ProtoRegistry/GetChannels", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *protoRegistryClient) SaveCluster(ctx context.Context, in *SaveClusterRequest, opts ...grpc.CallOption) (*SaveClusterReply, error) {
	out := new(SaveClusterReply)
	err := c.cc.Invoke(ctx, "/noptics.ProtoRegistry/SaveCluster", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *protoRegistryClient) GetCluster(ctx context.Context, in *GetClusterRequest, opts ...grpc.CallOption) (*GetClusterReply, error) {
	out := new(GetClusterReply)
	err := c.cc.Invoke(ctx, "/noptics.ProtoRegistry/GetCluster", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *protoRegistryClient) GetClusters(ctx context.Context, in *GetClustersRequest, opts ...grpc.CallOption) (*GetClustersReply, error) {
	out := new(GetClustersReply)
	err := c.cc.Invoke(ctx, "/noptics.ProtoRegistry/GetClusters", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProtoRegistryServer is the server API for ProtoRegistry service.
type ProtoRegistryServer interface {
	SaveFiles(context.Context, *SaveFilesRequest) (*SaveFilesReply, error)
	GetFiles(context.Context, *GetFilesRequest) (*GetFilesReply, error)
	SetMessage(context.Context, *SetMessageRequest) (*SetMessageReply, error)
	GetMessage(context.Context, *GetMessageRequest) (*GetMessageReply, error)
	GetChannelData(context.Context, *GetChannelDataRequest) (*GetChannelDataReply, error)
	SetChannelData(context.Context, *SetChannelDataRequest) (*SetChannelDataReply, error)
	GetChannels(context.Context, *GetChannelsRequest) (*GetChannelsReply, error)
	SaveCluster(context.Context, *SaveClusterRequest) (*SaveClusterReply, error)
	GetCluster(context.Context, *GetClusterRequest) (*GetClusterReply, error)
	GetClusters(context.Context, *GetClustersRequest) (*GetClustersReply, error)
}

func RegisterProtoRegistryServer(s *grpc.Server, srv ProtoRegistryServer) {
	s.RegisterService(&_ProtoRegistry_serviceDesc, srv)
}

func _ProtoRegistry_SaveFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProtoRegistryServer).SaveFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/noptics.ProtoRegistry/SaveFiles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProtoRegistryServer).SaveFiles(ctx, req.(*SaveFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProtoRegistry_GetFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProtoRegistryServer).GetFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/noptics.ProtoRegistry/GetFiles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProtoRegistryServer).GetFiles(ctx, req.(*GetFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProtoRegistry_SetMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProtoRegistryServer).SetMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/noptics.ProtoRegistry/SetMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProtoRegistryServer).SetMessage(ctx, req.(*SetMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProtoRegistry_GetMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProtoRegistryServer).GetMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/noptics.ProtoRegistry/GetMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProtoRegistryServer).GetMessage(ctx, req.(*GetMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProtoRegistry_GetChannelData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChannelDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProtoRegistryServer).GetChannelData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/noptics.ProtoRegistry/GetChannelData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProtoRegistryServer).GetChannelData(ctx, req.(*GetChannelDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProtoRegistry_SetChannelData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetChannelDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProtoRegistryServer).SetChannelData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/noptics.ProtoRegistry/SetChannelData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProtoRegistryServer).SetChannelData(ctx, req.(*SetChannelDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProtoRegistry_GetChannels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChannelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProtoRegistryServer).GetChannels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/noptics.ProtoRegistry/GetChannels",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProtoRegistryServer).GetChannels(ctx, req.(*GetChannelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProtoRegistry_SaveCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveClusterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProtoRegistryServer).SaveCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/noptics.ProtoRegistry/SaveCluster",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProtoRegistryServer).SaveCluster(ctx, req.(*SaveClusterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProtoRegistry_GetCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClusterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProtoRegistryServer).GetCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/noptics.ProtoRegistry/GetCluster",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProtoRegistryServer).GetCluster(ctx, req.(*GetClusterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProtoRegistry_GetClusters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClustersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProtoRegistryServer).GetClusters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/noptics.ProtoRegistry/GetClusters",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProtoRegistryServer).GetClusters(ctx, req.(*GetClustersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProtoRegistry_serviceDesc = grpc.ServiceDesc{
	ServiceName: "noptics.ProtoRegistry",
	HandlerType: (*ProtoRegistryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SaveFiles",
			Handler:    _ProtoRegistry_SaveFiles_Handler,
		},
		{
			MethodName: "GetFiles",
			Handler:    _ProtoRegistry_GetFiles_Handler,
		},
		{
			MethodName: "SetMessage",
			Handler:    _ProtoRegistry_SetMessage_Handler,
		},
		{
			MethodName: "GetMessage",
			Handler:    _ProtoRegistry_GetMessage_Handler,
		},
		{
			MethodName: "GetChannelData",
			Handler:    _ProtoRegistry_GetChannelData_Handler,
		},
		{
			MethodName: "SetChannelData",
			Handler:    _ProtoRegistry_SetChannelData_Handler,
		},
		{
			MethodName: "GetChannels",
			Handler:    _ProtoRegistry_GetChannels_Handler,
		},
		{
			MethodName: "SaveCluster",
			Handler:    _ProtoRegistry_SaveCluster_Handler,
		},
		{
			MethodName: "GetCluster",
			Handler:    _ProtoRegistry_GetCluster_Handler,
		},
		{
			MethodName: "GetClusters",
			Handler:    _ProtoRegistry_GetClusters_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "registry.proto",
}
